[versions]
kotlin = "1.9.21"
appcompat = "1.6.1"
coreKtx = "1.12.0"
ktor = "2.3.4"
kotlinx-datetime = "0.4.1"
sqlDelight = "1.5.5"
moko-mvvm = "0.16.1"
mokoResources = "0.23.0"
kamel = "0.7.3"
kermit = "2.0.2"
koin = "3.5.0"
koin-compose = "1.1.0"
activity = "1.8.1"
serialization = "1.6.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-androidx = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-loggin = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serilization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

moko-mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
moko-mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko-mvvm" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "mokoResources" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "mokoResources" }

sqldelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqldelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }

[plugins]
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "mokoResources" }