name:
  Build

on:
  push:
    branches-ignore:
      - "main"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Android
        run: ./gradlew androidApp:assembleDebug
  build_ios:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build iOS
        run: xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' build